words_to_imgify:
  type: list
  default: ""
  description: "A list of 'WORD,https://path.to/a.gif' pairs to be imgified"
excluded_tags:
  type: list
  list_type: compact
  default: "code|pre"
excluded_classes:
  type: list
  list_type: compact
  default: "onebox"
